config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'
  
  get 'landing/index'
  get 'landing/about'
  get 'landing/services'
  get 'landing/blog'
  get 'landing/news'
  get 'landing/contact'
  post 'landing/contact', to: 'landing#contact_post'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end

  def about
  end

  def services
  end

  def blog
  end

  def news
  end

  def contact
  end

  def contact_post
    redirect_to landing_index_path
  end

  #necesito un metodo para mostrar un mensaje de que se envio el formulario de contacto

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/views/landing/_contact_us.html.erb
<section class="mr-5 ml-5">
    <form action="<%=landing_contact_path %>" method="post">
    <%= token_tag %>
    <div class="form-group">
        <label for="exampleFormControlInput1">Por favor indicanos tu email de contacto</label>
        <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="email@ejemplo.com">
    </div>
    <div class="form-group">
        <label for="exampleFormControlSelect1">Eres empresa o persona natural</label>
        <select class="form-control" id="exampleFormControlSelect1">
        <option>Sin especificar</option>
        <option>Persona natural</option>
        <option>Empresa</option>
        </select>
    </div>
    <%# <div class="form-group">
        <label for="exampleFormControlSelect2">Example multiple select</label>
        <select multiple class="form-control" id="exampleFormControlSelect2">
        <option>1</option>
        <option>2</option>
        <option>3</option>
        <option>4</option>
        <option>5</option>
        </select>
    </div> %>
    <div class="form-group">
        <label for="exampleFormControlTextarea1">Cuentanos un poco sobre tu nivel actual de conocimiento de Bitcoin y el apoyo que te gustaria recibir por parte de un asesor como nosotros</label>
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Enviar</button>
    </form>
</section>

app/views/landing/about.html.erb
<h1>Sobre Nosotros</h1>


<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Doloremque, adipisci optio. Harum natus repellendus eum doloribus! Magnam ad fugiat nostrum, reiciendis quaerat molestias, error architecto, quos facere porro non asperiores?
</p>

<br>
<br>
<br>
<br>



<%= render 'contact_us' %>

app/views/landing/blog.html.erb
<h1>Landing#blog</h1>
<p>Find me in app/views/landing/blog.html.erb</p>

app/views/landing/contact.html.erb
<%= render 'contact_us' %>

app/views/landing/index.html.erb
<h1>Landing#index</h1>
<p>Find me in app/views/landing/index.html.erb</p>

app/views/landing/news.html.erb
<h1>Landing#news</h1>
<p>Find me in app/views/landing/news.html.erb</p>

app/views/landing/services.html.erb
<h1>Landing#services</h1>
<p>Find me in app/views/landing/services.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LDS Bitcoin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# Bootstrap 4.6 %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%# <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon"> %>
    <%= favicon_link_tag asset_path('logoOnly.png') %>
    
  </head>

  <body class="bg-dark text-white">
      <%#  Font-awesome bitcoin logo%>
      <%# <i class="fab fa-btc"></i> %>
      
      <%# <%= image_tag 'LDSlogo.png'%>
      
      
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" href="<%= root_path %> "> 
          <%= image_tag("logoOnly.png", height: '45', width: '45', class:"d-inline-block align-top" ) %>
          <!-- <img src="<%= image_tag 'LDSlogo.png'%>" width="30" height="30" class="d-inline-block align-top" alt=""> -->
          <span> LDS Bitcoin </span>
        </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto ">
          <li class="nav-item active">
            <a class="nav-link" href="<%=landing_contact_path%>">Contacto <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%=landing_about_path%>">Sobre Nosotros</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Servicios
            </a>
            <div class="dropdown-menu bg-dark " aria-labelledby="navbarDropdown">
              <a class="dropdown-item text-white" href="#">Para Personas Naturales</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item text-white" href="#">Para Asset Managers</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Blog/Noticias</a>
          </li>
        </ul>
      </div>
    </nav>


    <main class="mr-5 ml-5">
      <%= yield %>
    </main>


      <!-- Footer -->
        <hr>
        <div id="footer">
          <div class="container">
            <div class="row">
            </div>
            <hr />
            <div class="row">
              <div class="col-12">

                <!-- Contact -->
                  <section class="contact">
                    <header>
                      <h3>Aqui va el footer</h3>
                    </header>
                    <p>Urna nisl non quis interdum mus ornare ridiculus egestas ridiculus lobortis vivamus tempor aliquet.</p>
                    <ul class="icons">
                      <li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
                      <li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
                      <li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
                      <li><a href="#" class="icon brands fa-pinterest"><span class="label">Pinterest</span></a></li>
                      <li><a href="#" class="icon brands fa-dribbble"><span class="label">Dribbble</span></a></li>
                      <li><a href="#" class="icon brands fa-linkedin-in"><span class="label">Linkedin</span></a></li>
                    </ul>
                  </section>

                <!-- Copyright -->
                  <div class="copyright">
                    <ul class="menu">
                      <li>&copy; Untitled. All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
                    </ul>
                  </div>

              </div>

            </div>
          </div>
        </div>









  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

  </body>
</html>